using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.ResourceManagement;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Configuration;
using Robust.Shared.Utility;

namespace OpenDreamClient.States.Connecting;

[GenerateTypedNameReferences]
public sealed partial class ConnectingControl : Control {
    public ConnectingControl(IResourceCache resCache, IConfigurationManager configMan) {
        RobustXamlLoader.Load(this);

        Panel.PanelOverride = new StyleBoxFlat(Color.Black);

        ConnectingLabel.FontOverride = new VectorFont(resCache.GetResource<FontResource>("/Fonts/NotoSans-Regular.ttf"), 24);

        LayoutContainer.SetAnchorPreset(this, LayoutContainer.LayoutPreset.Wide);

        LayoutContainer.SetAnchorPreset(VBox, LayoutContainer.LayoutPreset.Center);
        LayoutContainer.SetGrowHorizontal(VBox, LayoutContainer.GrowDirection.Both);
        LayoutContainer.SetGrowVertical(VBox, LayoutContainer.GrowDirection.Both);

        LayoutContainer.SetAnchorPreset(ConnectingLabel, LayoutContainer.LayoutPreset.Center);
        LayoutContainer.SetGrowHorizontal(ConnectingLabel, LayoutContainer.GrowDirection.Both);
        LayoutContainer.SetGrowVertical(ConnectingLabel, LayoutContainer.GrowDirection.Both);

        var bgSpecifier = new SpriteSpecifier.Rsi(new ResPath("/Textures/Interface/background.rsi"), "background");
        Background.SetFromSpriteSpecifier(bgSpecifier);
        Background.DisplayRect.Stretch = TextureRect.StretchMode.KeepAspectCentered;
        LayoutContainer.SetAnchorPreset(Background, LayoutContainer.LayoutPreset.Wide);

    }
}
